### ISSUE TITLE
Doesn't cope with missing time window dates in inventory

### ISSUE THREAD

**Issue by pevans-gfz** [rizac/gfzreport#4]
While querying IRIS, I got a network with code XX, start time 2013-01-01, and no end time. This is probably not allowed for a temporary network, but happens anyway, and we should be generous in what we accept.

The offending request is http://service.iris.edu/fdsnws/station/1/query?maxlon=-23.84885&minlon=-61.7003&level=station&minlat=-64.0921&endbefore=2018-01-01T00:00:00&maxlat=15.541919
The offending network is XX "(PIC Test Data (PICTest))" and the station is XX.BB08 (X) at 18.58 S, 57.48 W.

**Comment by pevans-gfz** [comment]
Of course, in this case we might not actually want this station on the map. But `gfzreportgen` has no way of knowing if any of a data centre's stations might actually not be wanted (other than the exclusion for network code 'SY' in `templates/network/core/__init__.py`. We could change that to

`if net.code in ('SY', 'XX',):  # ignore synthetic and test data
`

but what other tricky networks are out there?

**Comment by rizac** [comment]
Fixed with commit 5a423c6 slightly modifying to your PR (thanks). Now start and end times are printed as question marks (do not even know why we need that time range btw ;-) )

On the server, git pull + restart the server, then-produce the report and see
