### ISSUE TITLE
Network map with nearby stations from other networks is over-full

### ISSUE THREAD

**Issue by pevans-gfz** [rizac/gfzreport#6]
For a temporary network, Figure 1, "Station distribution in experiment..." doesn't understand the time range constraint when there is a reused network code. For example:

![Screenshot-5M-Fig1_2020-09-10](https://user-images.githubusercontent.com/16350518/92721339-4058da00-f366-11ea-92b6-8f41a244903f.png)

We have [two 5M networks](https://geofon.gfz-potsdam.de/waveform/archive/network.php?ncode=5M),
* 5M:2015 (2015/2016) FOSA on the Cape Verde islands (green shading)
* 5M:2018: (2018/2020) BravoSeis in Antarctica (pink shading)

Expect: a report produced for each one of these should only show stations near that temporary network (and "whose activity period overlapped at least partially" in time). But the report generator Instead shows stations within a bounding box formed by *both* 5M networks.

**Comment by rizac** [comment]
Ok try to see how to fix it, gimme sime time ;-)

**Comment by pevans-gfz** [comment]
On 11.09.20 18:19, Riccardo Zaccarelli wrote:
> Ok try to see how to fix it, gimme sime time ;-)

Great. I think just check that the set of stations you choose
to include in the structure built by `geofonstations_df()`
only includes those from the network which exists in
the given year.

I'd rename the parameter `start_after_year` to just `year` or
`network_year`. Then select only the one network present
in geofon_inventory which is defined in that year.

* It's an error if there is none: "No network with code XX in year YYYY!"
* And it's different, messier FDSN-scale error if there is more than one.

Then go on building up the station list in `dframe` as before, from the
modified inventory.
